version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    server:
        build: .
        image: easyappointments-server:latest
        container_name: easyappointments-server
        depends_on:
            - mysql
        ports:
            - "8000:80"
        #volumes:
            #- ./:/var/www/html
            #- ./application:/var/www/html/application
            #- ./engine:/var/www/html/engine
            #- ./assets:/var/www/html/assets
            #- ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            #- ./server/config.php:/var/www/html/application/config/config.php
            #- ./server/constants.php:/var/www/html/application/config/constants.php
