version: "3.1"
services:
    server:
        image: us.gcr.io/coachyard-dev/easy-appts:SNAPSHOT
        container_name: easyappointments-server
        environment:
            - BASE_URL=${BASE_URL}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        ports:
            - "8000:80"