version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    server:
        build: .
        image: easyappointments-server:latest
        container_name: easyappointments-server
        environment:
            - DB_HOST=easyappointments-database:3306
            - DB_NAME=easyappointments
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - mysql
        ports:
            - "8000:80"
