version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./server/config.php:/var/www/html/application/config/config.php
            - ./server/constants.php:/var/www/html/application/config/constants.php
    admin-server:
        build: ./admin-server
        image: easyappointments-server:v1
        container_name: easyappointments-admin-server
        ports:
            - "8002:80"
        volumes:
            - ../:/var/www/html
            - ./admin-server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
            - ./admin-server/config.php:/var/www/html/application/config/config.php
            - ./admin-server/constants.php:/var/www/html/application/config/constants.php
